import { execFile } from "node:child_process"
import { realpathSync } from "node:fs"
import { dirname, isAbsolute, relative, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { promisify } from "node:util"
import { type AgentPlugin, createTool } from "@cline/sdk"

const execFileAsync = promisify(execFile)

const pluginRoot = dirname(fileURLToPath(import.meta.url))
const scriptsDir = resolve(pluginRoot, "scripts", "lib")

interface ValidateAwsDrawioInput {
	filePath?: string
	postProcess?: boolean
	previewUrl?: boolean
}

interface CommandResult {
	ok: boolean
	output: string
}

function errorMessage(error: unknown): string {
	return error instanceof Error ? error.message : String(error)
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value)
}

function parseInput(input: unknown): Required<ValidateAwsDrawioInput> {
	if (!isRecord(input)) {
		throw new Error("validate_aws_drawio input must be an object")
	}

	const filePath = typeof input.filePath === "string" ? input.filePath.trim() : ""
	if (!filePath) {
		throw new Error("filePath is required")
	}
	if (!/\.(drawio|drawio\.xml)$/i.test(filePath)) {
		throw new Error("filePath must end with .drawio or .drawio.xml")
	}

	return {
		filePath,
		postProcess: typeof input.postProcess === "boolean" ? input.postProcess : true,
		previewUrl: typeof input.previewUrl === "boolean" ? input.previewUrl : true,
	}
}

function resolveWorkspaceFile(workspaceRoot: string, filePath: string): string {
	const root = resolve(workspaceRoot)
	const target = isAbsolute(filePath) ? resolve(filePath) : resolve(root, filePath)
	let realRoot: string
	let realTarget: string
	try {
		realRoot = realpathSync(root)
		realTarget = realpathSync(target)
	} catch {
		const rel = relative(root, target)
		throw new Error(`filePath does not exist: ${rel || filePath}`)
	}
	const rel = relative(realRoot, realTarget)
	if (rel.startsWith("..") || isAbsolute(rel)) {
		throw new Error("filePath must resolve inside the workspace root")
	}
	return realTarget
}

function truncateOutput(output: string): string {
	return output.length > 12_000 ? `${output.slice(0, 12_000)}\n...truncated...` : output
}

async function runPython(scriptName: string, args: string[], cwd: string, timeoutMs = 10_000): Promise<CommandResult> {
	try {
		const result = await execFileAsync("python3", [resolve(scriptsDir, scriptName), ...args], {
			cwd,
			encoding: "utf8",
			maxBuffer: 1024 * 1024,
			timeout: timeoutMs,
		})
		return {
			ok: true,
			output: truncateOutput(`${result.stdout ?? ""}${result.stderr ?? ""}`.trim()),
		}
	} catch (error) {
		const err = error as { stdout?: string; stderr?: string }
		const output = `${err.stdout ?? ""}${err.stderr ?? ""}`.trim() || errorMessage(error)
		return { ok: false, output: truncateOutput(output) }
	}
}

async function hasDefusedXml(): Promise<boolean> {
	try {
		await execFileAsync("python3", ["-c", "import defusedxml"], {
			encoding: "utf8",
			timeout: 5_000,
		})
		return true
	} catch {
		return false
	}
}

function validateAwsDrawioTool(workspaceRoot: string | undefined) {
	return createTool<unknown, Record<string, unknown>>({
		name: "validate_aws_drawio",
		description:
			"Validate an AWS architecture .drawio file generated by the deploy-on-aws " +
			"diagram skill. Runs the bundled post-processor and XML/AWS4 shape validator " +
			"against a workspace file, then returns validation output and an optional " +
			"app.diagrams.net preview URL. Does not open a browser or call AWS.",
		inputSchema: {
			type: "object",
			properties: {
				filePath: {
					type: "string",
					description:
						"Workspace-relative or absolute path to a .drawio or .drawio.xml file. " +
						"The resolved path must stay inside the workspace root.",
				},
				postProcess: {
					type: "boolean",
					description:
						"Whether to run bundled deterministic fixers before validation. Defaults to true.",
				},
				previewUrl: {
					type: "boolean",
					description:
						"Whether to return an app.diagrams.net preview URL after validation passes. Defaults to true.",
				},
			},
			required: ["filePath"],
			additionalProperties: false,
		},
		timeoutMs: 30_000,
		retryable: false,
		execute: async (rawInput) => {
			const root = realpathSync(workspaceRoot?.trim() || process.cwd())
			let input: Required<ValidateAwsDrawioInput>
			let target: string
			try {
				input = parseInput(rawInput)
				target = resolveWorkspaceFile(root, input.filePath)
			} catch (error) {
				return { ok: false, error: errorMessage(error) }
			}

			if (!(await hasDefusedXml())) {
				return {
					ok: false,
					error: "Missing Python dependency defusedxml. Install it with: pip3 install 'defusedxml>=0.7.1'",
				}
			}

			const output: Record<string, unknown> = {
				ok: false,
				filePath: relative(root, target) || target,
			}

			if (input.postProcess) {
				const postProcess = await runPython("post_process_drawio.py", [target], root)
				output.postProcess = postProcess.output || "No post-processing output."
				if (!postProcess.ok) {
					output.error = "Post-processing failed"
					return output
				}
			}

			const validation = await runPython("validate_drawio.py", [target], root)
			output.validation = validation.output || "No validation output."
			output.ok = validation.ok && validation.output.includes("VALIDATION PASSED")
			if (!output.ok) {
				output.error = "Validation failed"
				return output
			}

			if (input.previewUrl) {
				const preview = await runPython("drawio_url.py", [target], root, 5_000)
				if (preview.ok && preview.output) {
					output.previewUrl = preview.output
				}
			}

			return output
		},
	})
}

const plugin: AgentPlugin = {
	name: "deploy-on-aws",
	manifest: {
		capabilities: ["skills", "mcp", "tools"],
	},

	setup(api, ctx) {
		api.registerMcpServer({
			name: "aws-knowledge",
			transport: {
				type: "streamableHttp",
				url: "https://knowledge-mcp.global.api.aws",
			},
		})
		api.registerMcpServer({
			name: "aws-pricing",
			transport: {
				type: "stdio",
				command: "uvx",
				args: ["awslabs.aws-pricing-mcp-server@1.0.31"],
				env: {
					FASTMCP_LOG_LEVEL: "ERROR",
				},
			},
		})
		api.registerMcpServer({
			name: "aws-iac",
			transport: {
				type: "stdio",
				command: "uvx",
				args: ["awslabs.aws-iac-mcp-server@1.0.19"],
			},
		})
		api.registerTool(validateAwsDrawioTool(ctx.workspaceInfo?.rootPath))
	},
}

export default plugin
